docs/index.md
docs/problems.md

- https://github.com/laminlabs/lamin-about/pull/14

🚚 Moved problems doc from `lamin-about` here

---

noxfile.py

- https://github.com/laminlabs/laminci/pull/9

:bento: Track README

---

noxfile.py

- https://github.com/laminlabs/bionty/pull/403

📝 Only use guide section of bionty

---

docs/faq/storage.md

- https://github.com/laminlabs/lamindb/pull/1022

📝 Populate storage FAQ

---

noxfile.py

- https://github.com/laminlabs/lamin-usecases/pull/30

📝 Move data lineage to use cases

---

docs/faq/storage.md

📝 Add s3 policies example for public instances

---

docs/access.md
noxfile.py

This starts with https://www.notion.so/laminlabs/App-Design-21-2023-10-03-d3ef134e2ef64ed6aa5abdb835c07295#b1843a02dbcd4d97a06f974fd8c18e49 and iterates on it.

📝 Add a section on access management & security

---

docs/features-lamindb.md
docs/features-laminhub.md
noxfile.py

Comes with this commit https://github.com/laminlabs/lamindb/commit/1b64b278323b7f07ac44c8ff35389f616238d705

🚚 Move features from lamindb docs here

---

docs/changelog/soon/lamindb.md

📝 Prepare lamindb 0.74.2 release notes

---

docs/introduction.ipynb

🍱 Update the process graph

---

docs/changelog/2024.md

- Adds more details for new perturbation use case to changelog

📝 Add perturbation use case changelog details

---

docs/changelog/2024.md

💄 Polish DB release 0.76.15

---

docs/changelog/2024.md
docs/changelog/soon/laminhub.md

Reverts laminlabs/lamin-docs#171

Revert "🔖 Release hub 0.30"

---

docs/changelog/2024.md
docs/changelog/soon/laminhub.md

Backfill from:
- https://github.com/laminlabs/laminhub-public/pull/15

🔖 Release hub 0.30, backfill hub release 0.29

---

docs/changelog/2024.md

Makes changes:
- https://github.com/laminlabs/lamin-docs/pull/180

🔖 Release DB 0.77 -- part 2

---

docs/integrations.md

Fixes https://github.com/laminlabs/lamin-docs/issues/170
- Adds all of our registries to the integrations page
- Encourages other people to reach out to have their registries featured

✨ Additional registries in integrations page 

---

.github/workflows/build.yml
docs/changelog/2024.md

🔖 Release hub 0.31

---

docs/tutorial2.ipynb
noxfile.py

Needs:
- https://github.com/laminlabs/lamindb/pull/2233

🩹 Minor polish `tutorial2`

---

docs/introduction.ipynb

Fixes https://github.com/laminlabs/lamindb/issues/2178#issuecomment-2580128692

🐛 Fix wrong name for cell type search

---

docs/changelog/2025.md
docs/changelog/soon/laminr.md

See:
- https://github.com/laminlabs/laminr/pull/154

🔖 LaminR 1.0

---

docs/introduction.ipynb

These should not be needed here

🎨 Remove pandas imports from intro

---

.pre-commit-config.yaml
_build/html/_redirects
docs/api.md
docs/includes/preface.md
docs/includes/py-quickstart.py
noxfile.py

- https://github.com/laminlabs/laminr/pull/170

♻️ Make R and Python quickstarts parallel

---

docs/access.md

Add examples on how to move into or create new entities in a selected space.

📝 Manage access in the API examples

---

docs/hubmap.ipynb

Updated the HuBMAP notebook with a new section for bulk RNA-seq datasets. I commented out the code so that it matches the previous cells. 
I am not sure why accessing the `Collection` fails, it ran perfectly fine for me.

♻️ Update the HuBMAP tutorial

---

docs/api.md
docs/laminr.md
docs/rest.md
docs/sql.md
noxfile.py

♻️ Different design left sidebar in API reference

---

.pre-commit-config.yaml
_build/html/llms.txt
noxfile.py

Needs: https://github.com/laminlabs/lndocs/commit/c668a578bd52bd6633c554297e2099f421401803
Follow-up for:
- https://github.com/laminlabs/lamin-docs/pull/270

🚚 Repurpose `llms.txt` to `summary.md` and create lightweight `llms.txt`

---

.gitignore
docs/includes/preface.md
docs/includes/py-quick-transfer.py
docs/includes/py-quickstart.py
docs/includes/quick-setup-lamindb.md

- https://github.com/laminlabs/lamindb/pull/2943

♻️ Simplify quickstart and add an actual README to LaminDB

---

docs/changelog/soon/laminhub.md

📝 Update changelog with new features and fixes

---

_build/html/_redirects
docs/guide.md
docs/ontologies.md
noxfile.py

Before | After
--- | ---
Comes with: 
- https://github.com/laminlabs/lamindb/pull/3103

📝 Show public ontologies and managing ontologies under one heading
